project:
  type: book
  output-dir: docs
  resources:
    - assets/
  post-render:
    - scripts/fix_crossref_punctuation.sh

lang: es

book:
  title: "DESCARTES Exp2 microbiome"
  site-url: "https://dcosimber.github.io/descartes_exp2/"
  sidebar:
    search: true
  author:
    - name: Daniel Costas
      orcid: 0000-0003-4384-8469
      email: daniel.costas.imbernon@gmail.com
      affiliations:
        - name: Instituto de Investigaciones Marinas (IIM-CSIC)
          city: Vigo
          state: Spain
          url: https://www.iim.csic.es
        - name: Aquabiotec Lab
          city: Vigo
          state: Spain
          url: https://acuabiotec.csic.es
  date: last-modified
  chapters:
    - index.qmd
    - chapters/01_introduction_objectives.qmd
    - chapters/02_experimental_design.qmd
    - chapters/03_dna_extraction_sequencing.qmd
    - chapters/04_preprocessing.qmd
    - chapters/05_filtering.qmd
    - chapters/06_dataset_stats.qmd
    - chapters/07_taxonomic_composition.qmd
    - chapters/08_alpha_diversity.qmd
    - chapters/09_beta_diversity.qmd
    - chapters/10_differential_abundance.qmd
    - chapters/11_functional_prediction.qmd
  appendices:
    - appendices/powerfecal_protocol.qmd
    - appendices/scripts/04_preprocessing/preprocessing_scripts.qmd
    - appendices/scripts/05_filtering/filtering_scripts.qmd
    - appendices/reproducibility.qmd

bibliography: references.bib
csl: vancouver-brackets.csl

format:
  html:
    toc: true
    toc-depth: 3
    toc-location: right
    tbl-cap-location: top
    fig-cap-location: bottom
    number-sections: true
    smooth-scroll: true
    anchor-sections: true
    link-external-newwindow: true
    lightbox:
      match: auto
      effect: zoom
      desc-position: bottom
    css: styles.css
    theme:
      light: cosmo
      dark: darkly

editor: visual
